KeyError in line 15 of /home/forster/Projects/Neoantigen_Prediction/Snakefile:
'type'
  File "/home/forster/Projects/Neoantigen_Prediction/Snakefile", line 15, in <module>
  File "/home/forster/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 4178, in set_index
  File "/home/forster/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
  File "/home/forster/miniconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
